FROM clojure:tools-deps

ARG APP_SERVER_PORT_CONTAINER
ARG APP_XTDB_PORT_CONTAINER
ARG APP_XTDB_URL

ENV APP_SERVER_PORT_CONTAINER=${APP_SERVER_PORT_CONTAINER}
ENV APP_XTDB_PORT_CONTAINER=${APP_XTDB_PORT_CONTAINER}
ENV APP_XTDB_URL=${APP_XTDB_URL}

RUN echo "APP_SERVER_PORT_CONTAINER is $APP_SERVER_PORT_CONTAINER"
RUN echo "APP_XTDB_PORT_CONTAINER is $APP_XTDB_PORT_CONTAINER"
RUN echo "APP_XTDB_URL is $APP_XTDB_URL"

EXPOSE ${APP_SERVER_PORT_CONTAINER}
EXPOSE ${APP_XTDB_PORT_CONTAINER}
#EXPOSE ${APP_XTDB_URL}

COPY . /usr/src/app
WORKDIR /usr/src/app/projects/usermanager

RUN clojure -T:build uber
